const TOGGLE_CHECKBOX = 'TOGGLE_CHECKBOX' as const
const TOGGLE_ALL_CHECKBOXES = 'TOGGLE_ALL_CHECKBOXES' as const
const TOGGLE_PRIORITY = 'TOGGLE_PRIORITY' as const
const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED' as const
const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING' as const
const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS' as const
<<<<<<< HEAD
const GET_FILTERED_TICKETS = 'GET_FILTERED_TICKETS' as const
const SET_PICKING_DATE = 'SET_PICKING_DATE' as const
const SET_SORTING_ITEMS = 'SET_SORTING_ITEMS' as const
=======
const GET_PORTION_OF_TICKETS = 'GET_PORTION_OF_TICKETS' as const
>>>>>>> 4765ca1df7fd38bb3540baf530403659cf0ea3ee

export const actionTypes = {
	TOGGLE_CHECKBOX,
	TOGGLE_ALL_CHECKBOXES,
	TOGGLE_PRIORITY,
	ITEMS_HAS_ERRORED,
	ITEMS_IS_LOADING,
	ITEMS_FETCH_DATA_SUCCESS,
<<<<<<< HEAD
	GET_FILTERED_TICKETS,
	SET_PICKING_DATE,
	SET_SORTING_ITEMS,
=======
	GET_PORTION_OF_TICKETS,
>>>>>>> 4765ca1df7fd38bb3540baf530403659cf0ea3ee
}
