const TOGGLE_CHECKBOX = 'TOGGLE_CHECKBOX' as const
const TOGGLE_ALL_CHECKBOXES = 'TOGGLE_ALL_CHECKBOXES' as const
const TOGGLE_PRIORITY = 'TOGGLE_PRIORITY' as const
const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED' as const
const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING' as const
const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS' as const
const SET_PICKING_DATE = 'SET_PICKING_DATE' as const
const SET_SORTING_ITEMS = 'SET_SORTING_ITEMS' as const
const SET_TICKET_PORTION = 'SET_TICKET_PORTION' as const
const ROLL_UP_MENU = 'ROLL_UP_MENU' as const

export const actionTypes = {
	TOGGLE_CHECKBOX,
	TOGGLE_ALL_CHECKBOXES,
	TOGGLE_PRIORITY,
	ITEMS_HAS_ERRORED,
	ITEMS_IS_LOADING,
	ITEMS_FETCH_DATA_SUCCESS,
	SET_PICKING_DATE,
	SET_SORTING_ITEMS,
	SET_TICKET_PORTION,
	ROLL_UP_MENU,
}
