const TOGGLE_CHECKBOX = 'TOGGLE_CHECKBOX' as const
const TOGGLE_ALL_CHECKBOXES = 'TOGGLE_ALL_CHECKBOXES' as const
const TOGGLE_PRIORITY = 'TOGGLE_PRIORITY' as const
const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED' as const
const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING' as const
const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS' as const
const GET_PORTION_OF_TICKETS = 'GET_PORTION_OF_TICKETS' as const

export const actionTypes = {
	TOGGLE_CHECKBOX,
	TOGGLE_ALL_CHECKBOXES,
	TOGGLE_PRIORITY,
	ITEMS_HAS_ERRORED,
	ITEMS_IS_LOADING,
	ITEMS_FETCH_DATA_SUCCESS,
	GET_PORTION_OF_TICKETS,
}
